# Generated by Django 4.1.7 on 2023-02-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('slug', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=150)),
                ('like', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Img',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=150)),
                ('comments_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=750)),
                ('point', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('place_id', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Open_Times',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opening_day', models.CharField(max_length=150)),
                ('opening_time', models.DateTimeField(max_length=150)),
                ('closing_time', models.DateTimeField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Img',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=150)),
                ('place_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place_SocialMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instagram', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('tiktok', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('place_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Places_Features',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wifi', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('bike_parking', models.BooleanField(default=False)),
                ('street_parking', models.BooleanField(default=False)),
                ('special', models.BooleanField(default=False)),
                ('wheelchair_wc', models.BooleanField(default=False)),
                ('wheelchair_ramp', models.BooleanField(default=False)),
                ('wheelchair_accesible', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('quide_line', models.BooleanField(default=False)),
                ('vegan_option', models.BooleanField(default=False)),
                ('for_kids', models.BooleanField(default=False)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('offers_delivery', models.BooleanField(default=False)),
                ('takes_rezervations', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booker', models.CharField(max_length=100)),
                ('time', models.DateTimeField(max_length=50)),
                ('day', models.DateTimeField(max_length=50)),
                ('place_id', models.CharField(max_length=100)),
                ('table_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instagram', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('tiktok', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Layout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_no', models.CharField(max_length=50)),
                ('number_of_chairs', models.CharField(max_length=50)),
                ('place_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1500)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('map_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('cover_img', models.CharField(max_length=150)),
                ('created_date', models.DateField()),
                ('slug', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.categories')),
            ],
        ),
    ]
