# Generated by Django 4.1.7 on 2023-02-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_places_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_img',
            name='comments_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place_img',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place_socialmedia',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='rezervation',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='rezervation',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='table_layout',
            name='place_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='Comment_Img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.comment_img'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.menu_category'),
        ),
        migrations.AddField(
            model_name='places',
            name='Comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.comments'),
        ),
        migrations.AddField(
            model_name='places',
            name='Menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.menu'),
        ),
        migrations.AddField(
            model_name='places',
            name='Open_Times',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.open_times'),
        ),
        migrations.AddField(
            model_name='places',
            name='Place_SocialMedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.place_socialmedia'),
        ),
        migrations.AddField(
            model_name='places',
            name='Places_Features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places_features'),
        ),
        migrations.AddField(
            model_name='places',
            name='Places_Img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.place_img'),
        ),
        migrations.AddField(
            model_name='places',
            name='Rezervation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.rezervation'),
        ),
        migrations.AddField(
            model_name='places',
            name='Table_Layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table_layout'),
        ),
        migrations.AddField(
            model_name='rezervation',
            name='Table_Layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table_layout'),
        ),
    ]
