# Generated by Django 4.1.7 on 2023-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_comment_img_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
