# Generated by Django 4.1.7 on 2023-02-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_places_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Comment_Img',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Open_Times',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Place_SocialMedia',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Places_Features',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Rezervation',
        ),
        migrations.AddField(
            model_name='comments',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='closing_time',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='opening_day',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='opening_time',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='places_features',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AddField(
            model_name='rezervation',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AlterField(
            model_name='place_img',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='Menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.menu'),
        ),
        migrations.AlterField(
            model_name='places',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Comment_Img',
        ),
        migrations.DeleteModel(
            name='Open_Times',
        ),
        migrations.DeleteModel(
            name='Place_SocialMedia',
        ),
    ]
