# Generated by Django 4.1.7 on 2023-02-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_comments_comment_img_remove_places_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezervation',
            old_name='day',
            new_name='finish_time',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Places_Img',
        ),
        migrations.RemoveField(
            model_name='places',
            name='Table_Layout',
        ),
        migrations.AddField(
            model_name='menu',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AddField(
            model_name='place_img',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AddField(
            model_name='table_layout',
            name='Places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
    ]
