# Generated by Django 4.1.7 on 2023-02-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_day_rezervation_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roles'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.categories'),
        ),
        migrations.AlterField(
            model_name='places',
            name='cover_img',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='is_home',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='is_open',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='map_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rezervation',
            name='Places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.places'),
        ),
    ]
