# Generated by Django 4.1.7 on 2023-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_user_roles_alter_menu_places_alter_places_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
