# Generated by Django 4.1.7 on 2023-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rezervation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='cover_img',
            field=models.ImageField(max_length=150, null=True, upload_to=''),
        ),
    ]
