# Generated by Django 4.1.7 on 2023-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_blogs_image_alter_comments_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervation',
            name='Places',
        ),
        migrations.AddField(
            model_name='rezervation',
            name='Places',
            field=models.ManyToManyField(to='booking.places'),
        ),
    ]
