# Generated by Django 4.1.7 on 2023-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_rezervation_places_rezervation_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='map_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
