# Generated by Django 4.1.7 on 2023-03-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='cities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.cities'),
        ),
    ]
